main:
  push:
    - docker:
        image: node:18
      imports: https://godgodgame.coding.net/p/tools/d/oci-private-key/git/tree/master/envs.yml
      stages:
        - name: 构建并打包
          script: | 
            mkdir archive
            tar --exclude='./archive' --exclude='.git' -zcvf archive/release.tar.gz .
        - name: ansible发布
          image: plugins/ansible
          settings:
            private_key: $HUAWEI_PRIVATE_KEY
            inventory: hosts
            playbook: playbook.yml
        