- name: My first play
  hosts: hostgroup
  remote_user: root
  tasks:
    - name: 复制到远程服务器
      copy:
        src: archive/release.tar.gz
        dest: /root/deploy/microsoft-rewards-script.tar.gz

    - name: 解压文件
      shell: |
        rm -rf /root/workspace/microsoft-rewards-script   
        mkdir /root/workspace/microsoft-rewards-script  
        tar -zxvf /root/deploy/microsoft-rewards-script.tar.gz -C /root/workspace/microsoft-rewards-script
        cp /root/deploy/microsoft-rewards-script-accounts.json /root/workspace/microsoft-rewards-script/src/accounts.json
      args:
        executable: /bin/bash
        
    - name: 构建
      shell: |
        cd /root/workspace/microsoft-rewards-script
        source /root/.nvm/nvm.sh
        nvm use v23.0.0
        npm install
        npm run build
      args:
        executable: /bin/bash

    - name: 运行脚本
      shell: |
        sudo chmod +x /root/workspace/microsoft-rewards-script/scripts/*.sh
        sudo cp -f /root/workspace/microsoft-rewards-script/scripts/crontab.template /etc/cron.d/microsoft-rewards-cron
        sudo chmod 644 /etc/cron.d/microsoft-rewards-cron
        sudo chown root:root /etc/cron.d/microsoft-rewards-cron
      args:
        executable: /bin/bash

