name: Login and Update Version
# 注意需要推送..所以要开启写入权限 Settings -> Actions -> General -> Workflow permissions:Read and write permissions
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # 每天两点运行

env:
  ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

jobs:
  login-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取所有历史记录，以确保我们可以推送

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Create accounts.json
        run: echo "$ACCOUNTS_JSON" > src/accounts.json

      - name: Update version.json
        run: |
          echo "{\"lastUpdated\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > .github/version.json

      - name: Login to website
        run: |
          set -e
          npm run build
          xvfb-run --server-args="-screen 0 1280x1024x24" npm run start

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/version.json
          git commit -m "Update version.json timestamp" || echo "No changes to commit"
          git push
